version: "3"
services: 
    postgres:
        image: "postgres:latest"
    redis:
        image: "redis:latest"
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./packages/nginx
        ports: 
            - "3050:80"
        depends_on: 
            - client
            - server
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./packages/server
        volumes: 
            - /server/node_modules
            - ./packages/server:/server
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_USER=postgres
            - PG_HOST=postgres
            - PG_DATABASE=postgres
            - PG_PASSWORD=postgres_password
            - PG_PORT=5432
        depends_on: 
            - postgres
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./packages/client
        volumes: 
            - /client/node_modules
            - ./packages/client:/client
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./packages/worker
        volumes: 
            - /worker/node_modules
            - ./packages/worker:/worker
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379